// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/jayantodpuji/grocerfy/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// FindUserByEmail provides a mock function with given fields: _a0, _a1
func (_m *MockUserRepository) FindUserByEmail(_a0 context.Context, _a1 string) (*models.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockUserRepository_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockUserRepository_Expecter) FindUserByEmail(_a0 interface{}, _a1 interface{}) *MockUserRepository_FindUserByEmail_Call {
	return &MockUserRepository_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", _a0, _a1)}
}

func (_c *MockUserRepository_FindUserByEmail_Call) Run(run func(_a0 context.Context, _a1 string)) *MockUserRepository_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindUserByEmail_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_FindUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserRepository_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// InsertRecord provides a mock function with given fields: _a0, _a1
func (_m *MockUserRepository) InsertRecord(_a0 context.Context, _a1 *models.User) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_InsertRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertRecord'
type MockUserRepository_InsertRecord_Call struct {
	*mock.Call
}

// InsertRecord is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *models.User
func (_e *MockUserRepository_Expecter) InsertRecord(_a0 interface{}, _a1 interface{}) *MockUserRepository_InsertRecord_Call {
	return &MockUserRepository_InsertRecord_Call{Call: _e.mock.On("InsertRecord", _a0, _a1)}
}

func (_c *MockUserRepository_InsertRecord_Call) Run(run func(_a0 context.Context, _a1 *models.User)) *MockUserRepository_InsertRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserRepository_InsertRecord_Call) Return(_a0 error) *MockUserRepository_InsertRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_InsertRecord_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockUserRepository_InsertRecord_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
